#!/bin/bash
#
# Convert Fahrenheit to Centigrade
for i in 10 20 30 40 50 60 70 80 90
do
  cent=$(( (${i}-32)*5/8 ))
  echo $i $cent
done  
echo 
echo "Now making use of the seq command" 
for i in `seq 10 10 90` 
do
  cent=$(( (${i}-32)*5/8 ))
  echo $i $cent
done

echo 
echo "Another method"
# Using c-like syntax ...
for (( i=10 ; i <= 90 ; i=i+10 ))
do
  cent=$(( (${i}-32)*5/8 ))
  echo $i $cent
done 

echo 
echo " Now back to front "
echo 
for (( i=90 ; i >= 10 ; i=i-10 ))
do
  cent=$(( (${i}-32)*5/8 ))
  echo $i $cent
done 
