#!/bin/bash
#SBATCH --chdir=.
#SBATCH -t 00:02:00
#
#  In this example we will attempt to merge the
#  normal output  *.o*  and error output *.e* files
#  for a job.
#    
#   
#  Your tasks are: 
#  
#  (1) Submit this script to the batch queue.
#  (2) Study the output. There is something wrong.
#      Locate the error and the error messages. 
#  (3) Use the appropriate qsub parameters to merge 
#      both the normal and error outputs into a single file
#      so that the location of the error is more easy to find.
#   
#


module use /usr/local/modulefiles/staging/eb/all/
module load ifort/2019.1.144-GCC-8.2.0-2.31.1


today=`date`
me=`whoami`
echo " The currently used shell is : $SHELL "
echo "This job was started on/time: $today  by $me "
echo 'This job was run on : ' $HOSTNAME
#rm a.out
ifort -o fish fish.f90 
 ./fish < fish1.in
 
