#!/bin/bash
#
# This is an example script for submitting mpi parallel jobs
# 
# Use this script as a template for your mpi jobs 
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4


module load apps/openmpi/4.0.1/binary




 mpirun ./diffuse  < testmpi.dat
