#!/bin/bash

# This example adds integer numbers together and prints out the result.
# It expects at least two parameters from the command line.
#
#  This is probably the most cryptic example. 
# It demonstrates the use of the ${@:start:length} method of accessing the command line parameters.   
#  Would it be possible to remove the for loop somehow ???
#
if [ $# -lt 2 ] 
then
  echo "Expecting at least two parameters."
else
 
  sum=0;
  for ((i=1; i<=$#;i++)) 
  do 
 #    echo ${@:i:1}
     sum=$((  sum+ ${@:i:1}  )) 
  done
fi 
echo " Sum of the numbers is:  $sum "
 


