#!/bin/bash 
#
#$ -j y
#$ -l h_rt=00:05:00
#
# This script will run the fish-stocks simulation 
# for a number of different enforcement limits.
# Modify this script so that as you repeatedly 
# run the simulation ( i.e. fish )for a set of 
# 'in this case 6' different input enforcement limits.
# you will send the output to a different file 
# for each run.
# 
limits='1500 2000 3000 4500 6000 7000'
for limit in $limits ;
 do 
  ( echo "$limit" | ./fish  )>> fishout 
 done
 





 

